config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :quetions do
    resources :answers
  end
  root to: "quetions#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :quetion
  has_many :attachments, as: :attachmentable

  validates :body, presence: true

  accepts_nested_attributes_for :attachments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :attachmentable, polymorphic: true

  mount_uploader :file, FileUploader
end

app/models/quetion.rb
class Quetion < ApplicationRecord
  validates :title, :body, presence: true

  has_many :answers
  has_many :attachments, as: :attachmentable

  accepts_nested_attributes_for :attachments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @quetion = Quetion.find(params[:quetion_id])
    @answer = @quetion.answers.build(answer_params)
    #redirect_to quetion_path(@quetion)
    respond_to do |format|
      if @answer.save
        format.html {render partial: 'quetions/answers', layout: false}
        format.json {render json: @answer }
        #format.js
      else
        format.html { render text: @answer.errors.full_massages.join("\n"), status: :umprocessable_entity }
        format.json { render json: @answer.errors.full_massages, status: :umprocessable_entity }
      end
    end
  end

  def update
    @answer=Answer.find(params[:id])
    @answer.update(answer_params)
    @quetion=@answer.quetion
    redirect_to quetion_path(@quetion)  
  end

  private

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:file] )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quetions_controller.rb
class QuetionsController < ApplicationController
  before_action :load_quetion, only: [:show,:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @quetions=Quetion.all
  end

  def show
    @answer = @quetion.answers.build
    @answer.attachments.build
  end

  def new
    @quetion=Quetion.new
    @quetion.attachments.build
  end

  def edit
    
  end

  def create
    @quetion=Quetion.new(quetion_params)

    if @quetion.save
      redirect_to @quetion
    else
      render :new
    end
  end

  def update
    if @quetion.update(quetion_params)
      redirect_to @quetion
    else
      render :edit
    end
  end

  def destroy
    @quetion.destroy
    redirect_to quetions_path
  end

  private

  def load_quetion
    @quetion=Quetion.find(params[:id])
  end

  def quetion_params
    params.require(:quetion).permit(:title,:body, attachments_attributes: [:file] )
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quetions_helper.rb
module QuetionsHelper
end

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message|%>
    $('.answer-errors').html('<%= j message %>')
  <% end %>
<% else %>
  $('.answers').html('<%= j render 'quetions/answers'%>');
  $('#answer_body').val('');
<% end %>

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message|%>
    $('.answer-errors').html('<%= j message %>')
  <% end %>
<% else %>
  $('.answers').html('<%= j render 'quetions/answers'%>');
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qna</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/quetions/_answers.html.slim
- @quetion.answers.each do |answer|
    - if answer.persisted?
        p= answer.body
        ul
            - answer.attachments.each do |a|
                li= link_to a.file.identifier, a.file.url
        -if user_signed_in?
            p= link_to 'Edit'
            p
                =form_for [@quetion, answer], remote: true do |f| 
                    =f.label :body, "Answer"
                    =f.text_area :body
                    =f.submit 'Save'

app/views/quetions/index.html.slim
p= link_to 'Ask quetion', new_quetion_path

app/views/quetions/new.html.slim
= form_for @quetion do |f|
  p
    = f.label :title, 'Title'
    = f.text_field :title
  p
    = f.label :body, 'Text'
    = f.text_area :body
  p Attachments:
  p
    = f.fields_for :attachments do |a|
      = a.label :file
      = a.file_field :file

  p= f.submit 'Create'

app/views/quetions/show.html.slim
h1= @quetion.title
p= @quetion.body
p Attachments:
ul
  - @quetion.attachments.each do |a|
    li= link_to a.file.identifier, a.file.url

.answers
  = render 'answers'

= form_for [@quetion, @answer], remote: true, data: { type: :json } do |f|
  p
    = f.label :body, 'You answer'
    .answer-errors      
    = f.text_area :body
  p
    =f.fields_for :attachments do |a|
      = a.label :file
      = a.file_field :file
    p= f.submit 'Create'